### ISSUE TITLE
Multiple licensing

### ISSUE THREAD

**Issue by elondaits** [hilbert/hilbert-ui#15]
1. hilbert-ui includes / uses some third party libraries that have their own licenses. Where should I list these? Some projects use a separate file for third party licenses, some bundle them all in the same place.
2. Would documentation and icons (or other images) be covered by our standard license or should we, somehow, specify an extra license such as CC-BY for those?

**Comment by porst17** [comment]
1. Why is it necessary to put the libraries into the git repository? Can't they be installed by some package manager similar to `npm`, but for the client side stuff? If it is really necessary to put the libs in there by hand, then put the corresponding license file in each subfolder, e.g. the jQuery license into [`client/public/lib/jquery`](https://github.com/hilbert/hilbert-ui/tree/master/client/public/lib/jquery). Then, add a notice to [`README.md#license`](https://github.com/hilbert/hilbert-ui/tree/e63b3a6aded52de53eafd2229a559c7520a0efbb#license) where to find the licenses for the libs. If the client side package managing needs more discussion, please open a new issue for it, similar to #14.
1. I think, we should use the same license for code, documentation as well as other resources in our project. Having multiple licenses has some drawbacks:
 1. We have to be careful that the individual licenses are compatible. The rights and responsibilities of the user are not as clear anymore (it's complicated enough even with a single license).
 1. It might be more difficult to upload our software to OSS repositories once the software has matured. Most platforms only offer the possibility to select a single license. Then you would need to split the package into several smaller ones, one per license.
 1. Some major OSS repositories like e.g. https://bintray.com/ don't even allow Creative Commons licenses, because *they should not be used for code* (and if we ship code and resources together this becomes a problem).
 Also, especially the non-copyleft licenses can be used to license documentation and other resources. Not sure about GPL-like licenses.  

 **Conclusion:** Same license for all files in the repository.

**Comment by porst17** [comment]
See #16 for an update of the license issue.

**Comment by elondaits** [comment]
Fixed in c366b734905bde945a5b020eb9010b51a535294d .
