### ISSUE TITLE
Dashboard should directly use Hilbert.yaml for configuration

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#26]

**Comment by elondaits** [comment]
Some requirements:

- Hilbert.yaml documentation (in a proper format)
- Sample valid hilbert.yaml
- Path of the hilbert.yaml file

Plus:

- Issue: The hilbert.yaml config format (and validation) is done via a complex Python script instead of a schema file. It's not easy to extend to add ui variables, and not easy to validate.
- Issue: the hilbert.yaml file could have been updated without re-syncing the stations so the hilbert ui server would be running under the new config while the back end would still be using the previous one (or vice versa!). Maintaining system integrity requires not updating the cfg while the UI Server is running and restarting the UI Server whenever the config is updated... but we can't expect end users to follow this rule correctly (or know about it).
- Issue: The hilbert.yaml file is compiled to a .pickle file (python serialization format), which the hilbert-cli reads, so there's an extra opportunity for being out of sync if the .yaml is newer / older than the .pickle.

**Comment by malex984** [comment]
Currently there is a env.var. `HILBERT_SERVER_CONFIG_PATH` which points to the museum configuration `Hilbert.yml` (e.g. `/HILBERT/Hilbert.yml`) (e.g. within a docker container running the Dashboard). This variable instructs the wrapper scripts where to get all the data from.

But i suppose there may be a similar preference at Dashboard server's config file, which i could specify when running Dashboard server inside a docker container?

Samples: 
https://github.com/hilbert/hilbert-cli/blob/feature/hilbert_server_misc/tests/data/Hilbert.yml
https://github.com/hilbert/hilbert-cli/blob/feature/hilbert_server_misc/tests/data/singleHostHilbert.yml

Documentation:
https://docs.google.com/document/d/1jZRIuSf0BXnUmjtuiKGFLWgz2dTfpPuYFOeRQmsJ0f0/edit#bookmark=id.3q753fckg58b

**Comment by malex984** [comment]
I currently have no schema for `Hilbert.yml` format. 
If it is necessary we can use some generic YAML validator e.g. https://github.com/Grokzen/pykwalify

But what exactly needs to be added into the current format for UI?

**Comment by malex984** [comment]
Currently `.pickle` files are used for internal tests only. They will not be generated by default (or by current wrapper scripts).

**Comment by porst17** [comment]
It seems to be easier and better to utilize the `hilbert-cli` script to extract the necessary information for the ui.
