### ISSUE TITLE
Info popup not visible in Firefox 59

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-ui#29]
If I click on the INFO icon of a station, nothing appears in Firefox (I tested 59). It works in Chrome 65.

**Comment by elondaits** [comment]
Here's the reason, leaving it here for reference later:
https://github.com/twbs/bootstrap/issues/11788

**Comment by porst17** [comment]
Is there a workaround for this?

**Comment by elondaits** [comment]
Possibly.
Most likely it's fixable by writing the event handlers manually. Right now the events are being handled by Bootstrap. The incompatibility is from using the "focus" event which is nice because it shows the popover when you click on a button and then hides it when you click on the button a second time (which is not the default). 
I suppose I could target the click handler and write the handlers myself, but this is a functionality I quickly implemented so that Alex had access to the station's ID and Description (which he asked for) and not having to write any code made it a whole lot easier.

**Comment by elondaits** [comment]
Fixed in ff3ecdc2d5c3c161b69fde0cb8dc9f4cf57814c9
